theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
rulers = [80, 100]
mouse = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

